### ISSUE TITLE
Hi Bro

### ISSUE THREAD

**Issue by alawasoft** [Karlovsky120/7DaysSaveManipulator#1]
Nice work on this, btw do you have any example on serializing the object to JSON format, because I found it too complicated to do it, or any advices? thanks :).

**Comment by Karlovsky120** [comment]
Thanks!
You can look at the source code and see what is what exactly and serialize just the things you need. Doing it all would take a bit of work. One of the guys who cloned the repo has created a partial phyton parser, so you might want to ask him. Not sure what his username is though.
